# -*- coding: utf-8 -*-
"""Rock, Paper, Scissors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WhoXJb8WtWEcZn0IS4jWDttuLtG1mRBj
"""

import random

def get_computer_choice():
    return random.choice(["rock", "paper", "scissors"])

def determine_winner(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "draw"
    elif (user_choice == "rock" and computer_choice == "scissors") or \
         (user_choice == "paper" and computer_choice == "rock") or \
         (user_choice == "scissors" and computer_choice == "paper"):
        return "win"
    else:
        return "lose"

def play_game():
    print("Welcome to Rock, Paper, Scissors!")
    while True:
        user_choice = input("Enter your choice (rock, paper, scissors or 'exit' to quit): ").lower()
        if user_choice == "exit":
            print("Thank you for playing!")
            break
        if user_choice not in ["rock", "paper", "scissors"]:
            print("Invalid choice. Please try again.")
            continue

        computer_choice = get_computer_choice()
        print(f"Computer chose: {computer_choice}")

        result = determine_winner(user_choice, computer_choice)
        if result == "draw":
            print("It's a draw!")
        elif result == "win":
            print("You win!")
        else:
            print("You lose!")
        print()

# Run the game
play_game()